### ISSUE TITLE
Cyberpunk 2077 IO Suite 1.6.1 Autofitter Broken

### ISSUE THREAD

**Issue by uglykidcid** [WolvenKit/Cyberpunk-Blender-add-on#195]
Cyberpunk 2077 IO Suite version 1.6.1 the autofitter is broken and no longer works for any body type. It receives a Python traceback error. If I reinstall the older version it works

**Comment by Simarilius-uk** [comment]
believe this is fixed in main, please test the build below
https://github.com/WolvenKit/Cyberpunk-Blender-add-on/actions/runs/12855741405

**Comment by DrSharky** [comment]
Still having issues with it. When trying to use the Autofitter, it doesn't apply the lattice object into the lattice modifier for me. When I run the Autofitter, it creates a modifier, creates the lattice, and then tries to apply the modifier as the shape key, but without first setting the created lattice as the lattice modifier's target object.
I added this bit of code to get it to work for me in the autofitter function right before `applyRefitter(mesh)`:

```
if lattice_modifier.object is None and new_lattice is not None:
            lattice_modifier.object = new_lattice
```


The addon feature in the Autofitter also doesn't work properly, the variables get mixed up. The script jsontool.py is trying to use the `function .endswith('.json')` on a boolean value, and the variable that gets fed into the function is `addon_target_body_path`.
I assume that variable shouldn't be the boolean, and the `useAddon` variable should be the boolean.
